screen -ls | grep -o '[0-9]*\.' | cut -d. -f1 | xargs -I {} screen -S {} -X quit
echo Starting bringup...
screen -dmS linorobot2_bringup "ros2 launch linorobot2_bringup bringup.launch.py"
echo Starting controller...
screen -dmS linorobot2_controller "ros2 launch teleop_twist_joy teleop-launch.py joy_config:=ps3"
echo Starting slam...
screen -dmS linorobot2_slam "ros2 launch linorobot2_navigation slam.launch.py"
echo Done.